//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayCampData
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbveventcountsbyunit
    {
        public int EventId { get; set; }
        public Nullable<decimal> VolCount { get; set; }
        public Nullable<decimal> RegCount { get; set; }
        public Nullable<decimal> ResCount { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string UnitType { get; set; }
        public int UnitNumber { get; set; }
    }
}
