//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayCampData
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbveventcount
    {
        public int EventId { get; set; }
        public string EventName { get; set; }
        public Nullable<long> VolunteerCount { get; set; }
        public Nullable<long> ReservationCount { get; set; }
        public Nullable<long> RegistrationCount { get; set; }
    }
}
