//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayCampData
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbvvolunteercount
    {
        public int events_EventID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int volunteerDays { get; set; }
        public string PersonType { get; set; }
        public string UnitType { get; set; }
        public int UnitNumber { get; set; }
        public int UnitID { get; set; }
    }
}
