//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayCampData
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventstaff
    {
        public int EventStaffID { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int positions_PositionID { get; set; }
        public int events_EventID { get; set; }
        public int person_PersonID { get; set; }
    
        public virtual position position { get; set; }
    }
}
