//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayCampData
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int PersonID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public int contactInfo_ContactInfoID { get; set; }
        public Nullable<int> ParentPersonID { get; set; }
        public int persontype_PersonTypeID { get; set; }
        public int unitranks_UnitRankID { get; set; }
        public int units_UnitID { get; set; }
        public string user_id { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
    
        public virtual contactinfo contactinfo { get; set; }
        public virtual persontype persontype { get; set; }
    }
}
