//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayCampData
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public int RegistrationID { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string Confirmation { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public int Events_EventID { get; set; }
        public int Person_PersonID { get; set; }
    }
}
