//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayCampData
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int ReservationID { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int Events_EventID { get; set; }
        public int Person_PersonID { get; set; }
        public string RegistrationCode { get; set; }
        public Nullable<System.DateTime> CodeExpiration { get; set; }
    }
}
