//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DBQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DBQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.DBQueries", typeof(DBQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delContactInfo.
        /// </summary>
        internal static string DelContactInfo {
            get {
                return ResourceManager.GetString("DelContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delEventType.
        /// </summary>
        internal static string DelEventType {
            get {
                return ResourceManager.GetString("DelEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delPersonType.
        /// </summary>
        internal static string DelPersonType {
            get {
                return ResourceManager.GetString("DelPersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delUnitType.
        /// </summary>
        internal static string DelUnitType {
            get {
                return ResourceManager.GetString("DelUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selContactInfo.
        /// </summary>
        internal static string GetContactInfo {
            get {
                return ResourceManager.GetString("GetContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selContactInfoByID.
        /// </summary>
        internal static string GetContactInfoById {
            get {
                return ResourceManager.GetString("GetContactInfoById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selEventTypes.
        /// </summary>
        internal static string GetEventType {
            get {
                return ResourceManager.GetString("GetEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selEventTypeByID.
        /// </summary>
        internal static string GetEventTypeById {
            get {
                return ResourceManager.GetString("GetEventTypeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selPersonType.
        /// </summary>
        internal static string GetPersonType {
            get {
                return ResourceManager.GetString("GetPersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selPersonTypeByID.
        /// </summary>
        internal static string GetPersonTypeById {
            get {
                return ResourceManager.GetString("GetPersonTypeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selUnitType.
        /// </summary>
        internal static string GetUnitType {
            get {
                return ResourceManager.GetString("GetUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selUnitTypeByID.
        /// </summary>
        internal static string GetUnitTypeById {
            get {
                return ResourceManager.GetString("GetUnitTypeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insContactInfo.
        /// </summary>
        internal static string InsContactInfo {
            get {
                return ResourceManager.GetString("InsContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insEventType.
        /// </summary>
        internal static string InsEventType {
            get {
                return ResourceManager.GetString("InsEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insPersonType.
        /// </summary>
        internal static string InsPersonType {
            get {
                return ResourceManager.GetString("InsPersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insUnitType.
        /// </summary>
        internal static string InsUnitType {
            get {
                return ResourceManager.GetString("InsUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updContactInfo.
        /// </summary>
        internal static string UpdContactInfo {
            get {
                return ResourceManager.GetString("UpdContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updEventType.
        /// </summary>
        internal static string UpdEventType {
            get {
                return ResourceManager.GetString("UpdEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updPersonType.
        /// </summary>
        internal static string UpdPersonType {
            get {
                return ResourceManager.GetString("UpdPersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updUnitType.
        /// </summary>
        internal static string UpdUnitType {
            get {
                return ResourceManager.GetString("UpdUnitType", resourceCulture);
            }
        }
    }
}
