//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DBQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DBQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.DBQueries", typeof(DBQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delContactInfo.
        /// </summary>
        internal static string DelContactInfo {
            get {
                return ResourceManager.GetString("DelContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delEvent.
        /// </summary>
        internal static string DelEvent {
            get {
                return ResourceManager.GetString("DelEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delEventStaff.
        /// </summary>
        internal static string DelEventStaff {
            get {
                return ResourceManager.GetString("DelEventStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delEventType.
        /// </summary>
        internal static string DelEventType {
            get {
                return ResourceManager.GetString("DelEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delEventVolunteers.
        /// </summary>
        internal static string DelEventVolunteer {
            get {
                return ResourceManager.GetString("DelEventVolunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delPerson.
        /// </summary>
        internal static string DelPerson {
            get {
                return ResourceManager.GetString("DelPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delPersonType.
        /// </summary>
        internal static string DelPersonType {
            get {
                return ResourceManager.GetString("DelPersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delPosition.
        /// </summary>
        internal static string DelPosition {
            get {
                return ResourceManager.GetString("DelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delRegistration.
        /// </summary>
        internal static string DelRegistration {
            get {
                return ResourceManager.GetString("DelRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delReservation.
        /// </summary>
        internal static string DelReservation {
            get {
                return ResourceManager.GetString("DelReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delUnit.
        /// </summary>
        internal static string DelUnit {
            get {
                return ResourceManager.GetString("DelUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delUnitRank.
        /// </summary>
        internal static string DelUnitRank {
            get {
                return ResourceManager.GetString("DelUnitRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delUnitType.
        /// </summary>
        internal static string DelUnitType {
            get {
                return ResourceManager.GetString("DelUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delVenue.
        /// </summary>
        internal static string DelVenue {
            get {
                return ResourceManager.GetString("DelVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selContactInfo.
        /// </summary>
        internal static string GetContactInfo {
            get {
                return ResourceManager.GetString("GetContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selContactInfoByID.
        /// </summary>
        internal static string GetContactInfoById {
            get {
                return ResourceManager.GetString("GetContactInfoById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selEventByID.
        /// </summary>
        internal static string GetEventById {
            get {
                return ResourceManager.GetString("GetEventById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selEvents.
        /// </summary>
        internal static string GetEvents {
            get {
                return ResourceManager.GetString("GetEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selEventStaff.
        /// </summary>
        internal static string GetEventStaff {
            get {
                return ResourceManager.GetString("GetEventStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selEventStaffByID.
        /// </summary>
        internal static string GetEventStaffById {
            get {
                return ResourceManager.GetString("GetEventStaffById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selEventTypes.
        /// </summary>
        internal static string GetEventType {
            get {
                return ResourceManager.GetString("GetEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selEventTypeByID.
        /// </summary>
        internal static string GetEventTypeById {
            get {
                return ResourceManager.GetString("GetEventTypeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selEventVolunteerByID.
        /// </summary>
        internal static string GetEventVolunteerById {
            get {
                return ResourceManager.GetString("GetEventVolunteerById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selEventVolunteers.
        /// </summary>
        internal static string GetEventVolunteers {
            get {
                return ResourceManager.GetString("GetEventVolunteers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selPersonByID.
        /// </summary>
        internal static string GetPersonById {
            get {
                return ResourceManager.GetString("GetPersonById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selPersons.
        /// </summary>
        internal static string GetPersons {
            get {
                return ResourceManager.GetString("GetPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selPersonType.
        /// </summary>
        internal static string GetPersonType {
            get {
                return ResourceManager.GetString("GetPersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selPersonTypeByID.
        /// </summary>
        internal static string GetPersonTypeById {
            get {
                return ResourceManager.GetString("GetPersonTypeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selPositions.
        /// </summary>
        internal static string GetPosition {
            get {
                return ResourceManager.GetString("GetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selPositionByID.
        /// </summary>
        internal static string GetPositionById {
            get {
                return ResourceManager.GetString("GetPositionById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selRegistrationByID.
        /// </summary>
        internal static string GetRegistrationById {
            get {
                return ResourceManager.GetString("GetRegistrationById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selRegistrations.
        /// </summary>
        internal static string GetRegistrations {
            get {
                return ResourceManager.GetString("GetRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selReservationByID.
        /// </summary>
        internal static string GetReservationById {
            get {
                return ResourceManager.GetString("GetReservationById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selReservations.
        /// </summary>
        internal static string GetReservations {
            get {
                return ResourceManager.GetString("GetReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selUnitByID.
        /// </summary>
        internal static string GetUnitById {
            get {
                return ResourceManager.GetString("GetUnitById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selUnitRankByID.
        /// </summary>
        internal static string GetUnitRankById {
            get {
                return ResourceManager.GetString("GetUnitRankById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selUnitRanks.
        /// </summary>
        internal static string GetUnitRanks {
            get {
                return ResourceManager.GetString("GetUnitRanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selUnits.
        /// </summary>
        internal static string GetUnits {
            get {
                return ResourceManager.GetString("GetUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selUnitType.
        /// </summary>
        internal static string GetUnitType {
            get {
                return ResourceManager.GetString("GetUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selUnitTypeByID.
        /// </summary>
        internal static string GetUnitTypeById {
            get {
                return ResourceManager.GetString("GetUnitTypeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selVenueByID.
        /// </summary>
        internal static string GetVenueById {
            get {
                return ResourceManager.GetString("GetVenueById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selVenues.
        /// </summary>
        internal static string GetVenues {
            get {
                return ResourceManager.GetString("GetVenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insContactInfo.
        /// </summary>
        internal static string InsContactInfo {
            get {
                return ResourceManager.GetString("InsContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insEvent.
        /// </summary>
        internal static string InsEvent {
            get {
                return ResourceManager.GetString("InsEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insEventStaff.
        /// </summary>
        internal static string InsEventStaff {
            get {
                return ResourceManager.GetString("InsEventStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insEventType.
        /// </summary>
        internal static string InsEventType {
            get {
                return ResourceManager.GetString("InsEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insEventVolunteer.
        /// </summary>
        internal static string InsEventVolunteer {
            get {
                return ResourceManager.GetString("InsEventVolunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insPerson.
        /// </summary>
        internal static string InsPerson {
            get {
                return ResourceManager.GetString("InsPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insPersonType.
        /// </summary>
        internal static string InsPersonType {
            get {
                return ResourceManager.GetString("InsPersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insPosition.
        /// </summary>
        internal static string InsPosition {
            get {
                return ResourceManager.GetString("InsPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insRegistration.
        /// </summary>
        internal static string InsRegistration {
            get {
                return ResourceManager.GetString("InsRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insReservation.
        /// </summary>
        internal static string InsReservation {
            get {
                return ResourceManager.GetString("InsReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insUnit.
        /// </summary>
        internal static string InsUnit {
            get {
                return ResourceManager.GetString("InsUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insUnitRank.
        /// </summary>
        internal static string InsUnitRank {
            get {
                return ResourceManager.GetString("InsUnitRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insUnitType.
        /// </summary>
        internal static string InsUnitType {
            get {
                return ResourceManager.GetString("InsUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insVenue.
        /// </summary>
        internal static string InsVenue {
            get {
                return ResourceManager.GetString("InsVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updContactInfo.
        /// </summary>
        internal static string UpdContactInfo {
            get {
                return ResourceManager.GetString("UpdContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updEvent.
        /// </summary>
        internal static string UpdEvent {
            get {
                return ResourceManager.GetString("UpdEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updEventStaff.
        /// </summary>
        internal static string UpdEventStaff {
            get {
                return ResourceManager.GetString("UpdEventStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updEventType.
        /// </summary>
        internal static string UpdEventType {
            get {
                return ResourceManager.GetString("UpdEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updEventVolunteer.
        /// </summary>
        internal static string UpdEventVolunteer {
            get {
                return ResourceManager.GetString("UpdEventVolunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updPerson.
        /// </summary>
        internal static string UpdPerson {
            get {
                return ResourceManager.GetString("UpdPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updPersonType.
        /// </summary>
        internal static string UpdPersonType {
            get {
                return ResourceManager.GetString("UpdPersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updPosition.
        /// </summary>
        internal static string UpdPosition {
            get {
                return ResourceManager.GetString("UpdPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updRegistration.
        /// </summary>
        internal static string UpdRegistration {
            get {
                return ResourceManager.GetString("UpdRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updReservation.
        /// </summary>
        internal static string UpdReservation {
            get {
                return ResourceManager.GetString("UpdReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updUnit.
        /// </summary>
        internal static string UpdUnit {
            get {
                return ResourceManager.GetString("UpdUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updUnitRank.
        /// </summary>
        internal static string UpdUnitRank {
            get {
                return ResourceManager.GetString("UpdUnitRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updUnitType.
        /// </summary>
        internal static string UpdUnitType {
            get {
                return ResourceManager.GetString("UpdUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updVenue.
        /// </summary>
        internal static string UpdVenue {
            get {
                return ResourceManager.GetString("UpdVenue", resourceCulture);
            }
        }
    }
}
